version: '3.7'

services:

  ui:
    container_name: ui
    build: ui
    volumes:
      - ./ui:/app
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    # command: sh -c "npm start && wait-for-it.sh localhost:3000 -- npm run test:visual"

  api:
    container_name: api
    build: api
    volumes:
      - ./api:/app
      - gradle_cache:/root/.gradle
    ports:
      - 8080:8080
    depends_on: 
      - database

  database:
    container_name: postgres
    image: postgres
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: memery

  e2e:
    container_name: e2e
    build: e2e
    volumes:
      - ./e2e:/app
    # command: sh -c "npm run serve & wait-for-it.sh localhost:3000 -- npm run test:visual"
    command: sh -c "wait-for-it.sh ui:3000 -- npm run test:visual"
    depends_on: 
      - ui

volumes:
  gradle_cache: