version: '3.7'

services:

  ui:
    container_name: ui
    build:
      context: ui/
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
