version: '3.7'

services:

  ui:
    container_name: ui
    build: ui
    volumes:
      - ./ui:/app
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development

  api:
    container_name: api
    build: api
    volumes:
      - ./api:/app
      - gradle_cache:/root/.gradle
    ports:
      - 8080:8080
volumes:
  gradle_cache: