name: CI

on:
  push:

jobs:

  build-test-api:

    runs-on: ubuntu-latest
    env:
      working-directory: ./api

    steps:
    - uses: actions/checkout@v2

    - name: Setup JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ${{env.working-directory}}

    - name: Build API
      run: ./gradlew build testClasses -x test -x integrationTest
      working-directory: ${{env.working-directory}}

    - name: Test API
      run: ./gradlew test
      working-directory: ${{env.working-directory}}

  build-test-ui:

    runs-on: ubuntu-latest
    env:
      working-directory: ./ui

    steps:
    - uses: actions/checkout@v2

    - name: Cache node modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install Dependencies
      run: npm install
      working-directory: ${{env.working-directory}}
    
    - name: Build UI
      run: npm run build
      working-directory: ${{env.working-directory}}

    - name: Test UI
      run: npm test
      working-directory: ${{env.working-directory}}
      env:
        CI: true